### ISSUE TITLE
Missing origin error

### ISSUE THREAD

**Issue by DogAndHerDude** [rs/cors#93] opened 2020-03-02 12:29 UTC
Guys, please, I'm all out of ideas. Nothing is working.

The basic issue is the fact that requests get denied because it says that `Access-Control-Allow-Origin` header is missing. Problem is that everything worked fine until it didn't for whatever reason. Some requests make it through, some just get ignored.

Here's my configuration to start with:

```go
	corsHandler := cors.New(cors.Options{
		AllowCredentials: true,
		AllowOriginFunc:  func(origin string) bool { return true },
		AllowedMethods:   []string{"GET", "POST", "PUT", "HEAD", "OPTIONS"},
		AllowedHeaders:   AllowedHeaders,
		Debug:            true,
	})
```

Whenever we receive a request in production, I get the following error:
`[cors] 2020/03/02 11:55:06 Actual request no headers added: missing origin`

If I log the origin in the `AllowOriginFunc` function, the origin is present.

The request itself is a basic `GET` method request using JS `fetch`:

```typescript
await fetch(new Request('<my url>', {
  method: 'GET',
  headers: {
   Accept: 'application/json',
  },
}))
```

**Comment by tarasyarema** [comment] 2020-03-19 13:04
Have you tried with `AllowedHeaders:   []string{"*"}`?

**Comment by mrsoftware** [comment] 2020-06-03 00:14
I have the same problem.

**Comment by GiancarlosIO** [comment] 2021-01-15 03:47
😢

**Comment by pierrebiver** [comment] 2021-02-07 14:11
Same here

**Comment by phramos07** [comment] 2021-02-23 01:01
Same here. In my case specifically, I have a Swagger-UI hosted on the same domain as my API. When it requests an endpoint, it gives me the message 'Failed to fetch'. In debug, I see that 'there is no origin header provided'. What's most intriguing is that, if I execute the exact `curl` that is  shown in the swagger-ui - supposedly the same Curl they're performing - I get an answer. So I know it's a CORS Problem, I've added CORS middleware, I've tested it locally with a fake `origin` header, but, in production, it fails. I don't know what to do anymore. Already checked the order in which I'm adding the middlewares and Cors is the first one.

**Comment by felipecruz91** [comment] 2021-02-25 20:36
I'm running out of ideas as well after +6h...

**Comment by mrsoftware** [comment] 2021-02-27 22:50
My problem was with proxy plugins, i was using proxy plugin in my browser, and that plugin was removing all headers about CORS, i disable it and now it's working.

**Comment by devinmatte** [comment] 2021-04-06 21:14
Having basically the same issue, just trying to send a simple fetch API call with an `Authorization` header. API call works fine before adding that header. The same log line is showing up `Actual request no headers added: missing origin`. `"Origin"` and `"Authorization"` are in my list of allowed headers.

**Comment by fangker** [comment] 2022-01-12 06:35
CORS  must set origin header.
 https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin

**Comment by hidayats10** [comment] 2022-06-04 19:13
Set the `cors.Options Debug` to `false`.

**Comment by mohdrasbi** [comment] 2022-06-13 12:13
> Set the `cors.Options Debug` to `false`.

This worked for me. Thanks @hidayats10!

**Comment by zee7153** [comment] 2022-10-03 11:58
same issue i face

**Comment by TRSeculan** [comment] 2023-12-20 03:47
does anyone solve this ?

**Comment by NekoFluff** [comment] 2023-12-23 20:18
> > Set the `cors.Options Debug` to `false`.
> 
> Doesn't that just keep the error message from appearing in the output? _(i.e. it does not resolve the underlying problem)_

Strangely enough I started getting response data after setting the Debug option to false so that's that.

**Comment by jub0bs** [comment] 2023-12-30 22:09
I'm not blaming anybody, but there seems to be much confusion in this issue. The lack of a minimal reproducible example doesn't help. Here is my two cents.

As of v1.10.1 (at least), the following message is logged

> Actual request no headers added: missing origin

only if

1. the `Debug` option is set, and
2. the request lacks an `Origin` header, i.e. is a same-origin request.

If the request is same-origin, it simply doesn't participate in the CORS protocol and there's no need for any `Access-Control-Allow-Origin` header in the response. The log message above does not indicate that your CORS middleware is well configured or misconfigured.

---

@NekoFluff

> Strangely enough I started getting response data after setting the Debug option to false so that's that.

I'd be very curious to see a minimal reproducible example (perhaps in the form of one or two tests cases; see `cors_test.go`).

**Comment by jub0bs** [comment] 2024-06-26 17:47
@rs In the absence of feedback from the OP or later commenters, I think that you could close this issue.

**Closed** 2024-06-26 18:47 UTC
