### ISSUE TITLE
Error on when getting repo with Godeps

### ISSUE THREAD

**Issue by adayag** [rs/cors#11] opened 2015-07-24 20:16 UTC
```
[ec2-107-20-94-2.compute-1.amazonaws.com] out: src/github.com/rs/cors/cors.go:121: undefined: strings.IndexByte
[ec2-107-20-94-2.compute-1.amazonaws.com] out:


Fatal error: run() received nonzero return code 2 while executing!
```

Last commit introduced this error when trying to get my repo using godeps

**Comment by rs** [comment] 2015-07-27 12:08
Which version of go are you running? The `strings.IndexByte` function is provided by the go standard library.

**Comment by elithrar** [comment] 2015-09-12 02:03
Note that `strings.IndexByte` was added in Go 1.2 as per https://github.com/go-sql-driver/mysql/issues/316 - which would put you on a very old version of Go (>1.5 years old).

**Comment by rs** [comment] 2015-09-12 02:35
I will close this issue. If the issue is not related to go version, please reopen.

**Closed by rs** 2015-09-12 02:35 UTC
